[package]
name = "neko"
version = "0.1.0"
authors = ["cyw <weems1995@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
